/* Generated by Color Studio v2.1.0 */

struct MurielPalette {
    static func color(from key: String) -> UIColor? {
        switch key {
        case "White":
            return UIColor(red: 255/255.0, green: 255/255.0, blue: 255/255.0, alpha: 1)
        case "Black":
            return UIColor(red: 0/255.0, green: 0/255.0, blue: 0/255.0, alpha: 1)

        case "Gray0":
            return UIColor(red: 246/255.0, green: 247/255.0, blue: 247/255.0, alpha: 1)
        case "Gray5":
            return UIColor(red: 220/255.0, green: 220/255.0, blue: 222/255.0, alpha: 1)
        case "Gray10":
            return UIColor(red: 195/255.0, green: 196/255.0, blue: 199/255.0, alpha: 1)
        case "Gray20":
            return UIColor(red: 167/255.0, green: 170/255.0, blue: 173/255.0, alpha: 1)
        case "Gray30":
            return UIColor(red: 142/255.0, green: 145/255.0, blue: 150/255.0, alpha: 1)
        case "Gray40":
            return UIColor(red: 120/255.0, green: 124/255.0, blue: 130/255.0, alpha: 1)
        case "Gray50":
            return UIColor(red: 100/255.0, green: 105/255.0, blue: 112/255.0, alpha: 1)
        case "Gray60":
            return UIColor(red: 80/255.0, green: 87/255.0, blue: 94/255.0, alpha: 1)
        case "Gray70":
            return UIColor(red: 60/255.0, green: 67/255.0, blue: 74/255.0, alpha: 1)
        case "Gray80":
            return UIColor(red: 44/255.0, green: 51/255.0, blue: 56/255.0, alpha: 1)
        case "Gray90":
            return UIColor(red: 29/255.0, green: 35/255.0, blue: 39/255.0, alpha: 1)
        case "Gray100":
            return UIColor(red: 16/255.0, green: 21/255.0, blue: 23/255.0, alpha: 1)
        case "Gray":
            return UIColor(red: 100/255.0, green: 105/255.0, blue: 112/255.0, alpha: 1)

        case "Blue0":
            return UIColor(red: 239/255.0, green: 243/255.0, blue: 247/255.0, alpha: 1)
        case "Blue5":
            return UIColor(red: 198/255.0, green: 222/255.0, blue: 246/255.0, alpha: 1)
        case "Blue10":
            return UIColor(red: 154/255.0, green: 198/255.0, blue: 240/255.0, alpha: 1)
        case "Blue20":
            return UIColor(red: 114/255.0, green: 174/255.0, blue: 230/255.0, alpha: 1)
        case "Blue30":
            return UIColor(red: 81/255.0, green: 152/255.0, blue: 217/255.0, alpha: 1)
        case "Blue40":
            return UIColor(red: 53/255.0, green: 130/255.0, blue: 196/255.0, alpha: 1)
        case "Blue50":
            return UIColor(red: 34/255.0, green: 113/255.0, blue: 177/255.0, alpha: 1)
        case "Blue60":
            return UIColor(red: 19/255.0, green: 94/255.0, blue: 150/255.0, alpha: 1)
        case "Blue70":
            return UIColor(red: 10/255.0, green: 75/255.0, blue: 120/255.0, alpha: 1)
        case "Blue80":
            return UIColor(red: 4/255.0, green: 57/255.0, blue: 89/255.0, alpha: 1)
        case "Blue90":
            return UIColor(red: 1/255.0, green: 38/255.0, blue: 58/255.0, alpha: 1)
        case "Blue100":
            return UIColor(red: 0/255.0, green: 19/255.0, blue: 28/255.0, alpha: 1)
        case "Blue":
            return UIColor(red: 34/255.0, green: 113/255.0, blue: 177/255.0, alpha: 1)

        case "Purple0":
            return UIColor(red: 242/255.0, green: 236/255.0, blue: 239/255.0, alpha: 1)
        case "Purple5":
            return UIColor(red: 240/255.0, green: 209/255.0, blue: 228/255.0, alpha: 1)
        case "Purple10":
            return UIColor(red: 227/255.0, green: 174/255.0, blue: 212/255.0, alpha: 1)
        case "Purple20":
            return UIColor(red: 212/255.0, green: 143/255.0, blue: 200/255.0, alpha: 1)
        case "Purple30":
            return UIColor(red: 196/255.0, green: 117/255.0, blue: 189/255.0, alpha: 1)
        case "Purple40":
            return UIColor(red: 179/255.0, green: 94/255.0, blue: 177/255.0, alpha: 1)
        case "Purple50":
            return UIColor(red: 152/255.0, green: 74/255.0, blue: 156/255.0, alpha: 1)
        case "Purple60":
            return UIColor(red: 124/255.0, green: 57/255.0, blue: 130/255.0, alpha: 1)
        case "Purple70":
            return UIColor(red: 102/255.0, green: 44/255.0, blue: 110/255.0, alpha: 1)
        case "Purple80":
            return UIColor(red: 77/255.0, green: 32/255.0, blue: 84/255.0, alpha: 1)
        case "Purple90":
            return UIColor(red: 53/255.0, green: 22/255.0, blue: 59/255.0, alpha: 1)
        case "Purple100":
            return UIColor(red: 30/255.0, green: 12/255.0, blue: 33/255.0, alpha: 1)
        case "Purple":
            return UIColor(red: 152/255.0, green: 74/255.0, blue: 156/255.0, alpha: 1)

        case "Pink0":
            return UIColor(red: 245/255.0, green: 236/255.0, blue: 239/255.0, alpha: 1)
        case "Pink5":
            return UIColor(red: 250/255.0, green: 204/255.0, blue: 220/255.0, alpha: 1)
        case "Pink10":
            return UIColor(red: 247/255.0, green: 166/255.0, blue: 194/255.0, alpha: 1)
        case "Pink20":
            return UIColor(red: 242/255.0, green: 131/255.0, blue: 170/255.0, alpha: 1)
        case "Pink30":
            return UIColor(red: 235/255.0, green: 101/255.0, blue: 148/255.0, alpha: 1)
        case "Pink40":
            return UIColor(red: 227/255.0, green: 76/255.0, blue: 132/255.0, alpha: 1)
        case "Pink50":
            return UIColor(red: 201/255.0, green: 53/255.0, blue: 110/255.0, alpha: 1)
        case "Pink60":
            return UIColor(red: 171/255.0, green: 35/255.0, blue: 90/255.0, alpha: 1)
        case "Pink70":
            return UIColor(red: 140/255.0, green: 23/255.0, blue: 73/255.0, alpha: 1)
        case "Pink80":
            return UIColor(red: 112/255.0, green: 15/255.0, blue: 59/255.0, alpha: 1)
        case "Pink90":
            return UIColor(red: 79/255.0, green: 9/255.0, blue: 42/255.0, alpha: 1)
        case "Pink100":
            return UIColor(red: 38/255.0, green: 4/255.0, blue: 21/255.0, alpha: 1)
        case "Pink":
            return UIColor(red: 201/255.0, green: 53/255.0, blue: 110/255.0, alpha: 1)

        case "Red0":
            return UIColor(red: 247/255.0, green: 237/255.0, blue: 238/255.0, alpha: 1)
        case "Red5":
            return UIColor(red: 255/255.0, green: 204/255.0, blue: 208/255.0, alpha: 1)
        case "Red10":
            return UIColor(red: 255/255.0, green: 166/255.0, blue: 171/255.0, alpha: 1)
        case "Red20":
            return UIColor(red: 255/255.0, green: 128/255.0, blue: 133/255.0, alpha: 1)
        case "Red30":
            return UIColor(red: 248/255.0, green: 99/255.0, blue: 104/255.0, alpha: 1)
        case "Red40":
            return UIColor(red: 230/255.0, green: 80/255.0, blue: 84/255.0, alpha: 1)
        case "Red50":
            return UIColor(red: 214/255.0, green: 54/255.0, blue: 56/255.0, alpha: 1)
        case "Red60":
            return UIColor(red: 179/255.0, green: 45/255.0, blue: 46/255.0, alpha: 1)
        case "Red70":
            return UIColor(red: 138/255.0, green: 36/255.0, blue: 36/255.0, alpha: 1)
        case "Red80":
            return UIColor(red: 105/255.0, green: 28/255.0, blue: 28/255.0, alpha: 1)
        case "Red90":
            return UIColor(red: 69/255.0, green: 19/255.0, blue: 19/255.0, alpha: 1)
        case "Red100":
            return UIColor(red: 36/255.0, green: 10/255.0, blue: 10/255.0, alpha: 1)
        case "Red":
            return UIColor(red: 214/255.0, green: 54/255.0, blue: 56/255.0, alpha: 1)

        case "Orange0":
            return UIColor(red: 247/255.0, green: 240/255.0, blue: 234/255.0, alpha: 1)
        case "Orange5":
            return UIColor(red: 252/255.0, green: 215/255.0, blue: 186/255.0, alpha: 1)
        case "Orange10":
            return UIColor(red: 255/255.0, green: 191/255.0, blue: 134/255.0, alpha: 1)
        case "Orange20":
            return UIColor(red: 250/255.0, green: 167/255.0, blue: 84/255.0, alpha: 1)
        case "Orange30":
            return UIColor(red: 230/255.0, green: 139/255.0, blue: 40/255.0, alpha: 1)
        case "Orange40":
            return UIColor(red: 214/255.0, green: 119/255.0, blue: 9/255.0, alpha: 1)
        case "Orange50":
            return UIColor(red: 178/255.0, green: 98/255.0, blue: 0/255.0, alpha: 1)
        case "Orange60":
            return UIColor(red: 138/255.0, green: 77/255.0, blue: 0/255.0, alpha: 1)
        case "Orange70":
            return UIColor(red: 112/255.0, green: 64/255.0, blue: 0/255.0, alpha: 1)
        case "Orange80":
            return UIColor(red: 84/255.0, green: 49/255.0, blue: 0/255.0, alpha: 1)
        case "Orange90":
            return UIColor(red: 54/255.0, green: 31/255.0, blue: 0/255.0, alpha: 1)
        case "Orange100":
            return UIColor(red: 31/255.0, green: 18/255.0, blue: 0/255.0, alpha: 1)
        case "Orange":
            return UIColor(red: 178/255.0, green: 98/255.0, blue: 0/255.0, alpha: 1)

        case "Yellow0":
            return UIColor(red: 247/255.0, green: 242/255.0, blue: 230/255.0, alpha: 1)
        case "Yellow5":
            return UIColor(red: 247/255.0, green: 225/255.0, blue: 174/255.0, alpha: 1)
        case "Yellow10":
            return UIColor(red: 242/255.0, green: 207/255.0, blue: 117/255.0, alpha: 1)
        case "Yellow20":
            return UIColor(red: 240/255.0, green: 196/255.0, blue: 67/255.0, alpha: 1)
        case "Yellow30":
            return UIColor(red: 219/255.0, green: 174/255.0, blue: 23/255.0, alpha: 1)
        case "Yellow40":
            return UIColor(red: 182/255.0, green: 144/255.0, blue: 0/255.0, alpha: 1)
        case "Yellow50":
            return UIColor(red: 144/255.0, green: 115/255.0, blue: 0/255.0, alpha: 1)
        case "Yellow60":
            return UIColor(red: 112/255.0, green: 91/255.0, blue: 0/255.0, alpha: 1)
        case "Yellow70":
            return UIColor(red: 92/255.0, green: 75/255.0, blue: 0/255.0, alpha: 1)
        case "Yellow80":
            return UIColor(red: 69/255.0, green: 57/255.0, blue: 0/255.0, alpha: 1)
        case "Yellow90":
            return UIColor(red: 48/255.0, green: 40/255.0, blue: 0/255.0, alpha: 1)
        case "Yellow100":
            return UIColor(red: 28/255.0, green: 23/255.0, blue: 0/255.0, alpha: 1)
        case "Yellow":
            return UIColor(red: 144/255.0, green: 115/255.0, blue: 0/255.0, alpha: 1)

        case "Green0":
            return UIColor(red: 235/255.0, green: 247/255.0, blue: 241/255.0, alpha: 1)
        case "Green5":
            return UIColor(red: 164/255.0, green: 245/255.0, blue: 200/255.0, alpha: 1)
        case "Green10":
            return UIColor(red: 89/255.0, green: 227/255.0, blue: 143/255.0, alpha: 1)
        case "Green20":
            return UIColor(red: 30/255.0, green: 209/255.0, blue: 90/255.0, alpha: 1)
        case "Green30":
            return UIColor(red: 0/255.0, green: 186/255.0, blue: 55/255.0, alpha: 1)
        case "Green40":
            return UIColor(red: 0/255.0, green: 163/255.0, blue: 42/255.0, alpha: 1)
        case "Green50":
            return UIColor(red: 0/255.0, green: 138/255.0, blue: 32/255.0, alpha: 1)
        case "Green60":
            return UIColor(red: 0/255.0, green: 112/255.0, blue: 23/255.0, alpha: 1)
        case "Green70":
            return UIColor(red: 0/255.0, green: 92/255.0, blue: 18/255.0, alpha: 1)
        case "Green80":
            return UIColor(red: 0/255.0, green: 69/255.0, blue: 12/255.0, alpha: 1)
        case "Green90":
            return UIColor(red: 0/255.0, green: 48/255.0, blue: 8/255.0, alpha: 1)
        case "Green100":
            return UIColor(red: 0/255.0, green: 28/255.0, blue: 5/255.0, alpha: 1)
        case "Green":
            return UIColor(red: 0/255.0, green: 138/255.0, blue: 32/255.0, alpha: 1)

        case "Celadon0":
            return UIColor(red: 236/255.0, green: 247/255.0, blue: 244/255.0, alpha: 1)
        case "Celadon5":
            return UIColor(red: 166/255.0, green: 235/255.0, blue: 214/255.0, alpha: 1)
        case "Celadon10":
            return UIColor(red: 99/255.0, green: 214/255.0, blue: 182/255.0, alpha: 1)
        case "Celadon20":
            return UIColor(red: 46/255.0, green: 189/255.0, blue: 153/255.0, alpha: 1)
        case "Celadon30":
            return UIColor(red: 9/255.0, green: 168/255.0, blue: 132/255.0, alpha: 1)
        case "Celadon40":
            return UIColor(red: 0/255.0, green: 145/255.0, blue: 114/255.0, alpha: 1)
        case "Celadon50":
            return UIColor(red: 0/255.0, green: 126/255.0, blue: 101/255.0, alpha: 1)
        case "Celadon60":
            return UIColor(red: 0/255.0, green: 103/255.0, blue: 83/255.0, alpha: 1)
        case "Celadon70":
            return UIColor(red: 0/255.0, green: 80/255.0, blue: 66/255.0, alpha: 1)
        case "Celadon80":
            return UIColor(red: 0/255.0, green: 59/255.0, blue: 48/255.0, alpha: 1)
        case "Celadon90":
            return UIColor(red: 0/255.0, green: 39/255.0, blue: 33/255.0, alpha: 1)
        case "Celadon100":
            return UIColor(red: 0/255.0, green: 28/255.0, blue: 23/255.0, alpha: 1)
        case "Celadon":
            return UIColor(red: 0/255.0, green: 126/255.0, blue: 101/255.0, alpha: 1)

        case "WordPressBlue0":
            return UIColor(red: 233/255.0, green: 243/255.0, blue: 247/255.0, alpha: 1)
        case "WordPressBlue5":
            return UIColor(red: 193/255.0, green: 225/255.0, blue: 238/255.0, alpha: 1)
        case "WordPressBlue10":
            return UIColor(red: 153/255.0, green: 205/255.0, blue: 225/255.0, alpha: 1)
        case "WordPressBlue20":
            return UIColor(red: 106/255.0, green: 179/255.0, blue: 208/255.0, alpha: 1)
        case "WordPressBlue30":
            return UIColor(red: 56/255.0, green: 149/255.0, blue: 186/255.0, alpha: 1)
        case "WordPressBlue40":
            return UIColor(red: 24/255.0, green: 122/255.0, blue: 162/255.0, alpha: 1)
        case "WordPressBlue50":
            return UIColor(red: 0/255.0, green: 96/255.0, blue: 136/255.0, alpha: 1)
        case "WordPressBlue60":
            return UIColor(red: 0/255.0, green: 78/255.0, blue: 110/255.0, alpha: 1)
        case "WordPressBlue70":
            return UIColor(red: 0/255.0, green: 60/255.0, blue: 86/255.0, alpha: 1)
        case "WordPressBlue80":
            return UIColor(red: 0/255.0, green: 44/255.0, blue: 64/255.0, alpha: 1)
        case "WordPressBlue90":
            return UIColor(red: 0/255.0, green: 29/255.0, blue: 45/255.0, alpha: 1)
        case "WordPressBlue100":
            return UIColor(red: 0/255.0, green: 16/255.0, blue: 28/255.0, alpha: 1)
        case "WordPressBlue":
            return UIColor(red: 0/255.0, green: 96/255.0, blue: 136/255.0, alpha: 1)

        case "WooCommercePurple0":
            return UIColor(red: 245/255.0, green: 233/255.0, blue: 245/255.0, alpha: 1)
        case "WooCommercePurple5":
            return UIColor(red: 236/255.0, green: 204/255.0, blue: 240/255.0, alpha: 1)
        case "WooCommercePurple10":
            return UIColor(red: 221/255.0, green: 176/255.0, blue: 235/255.0, alpha: 1)
        case "WooCommercePurple20":
            return UIColor(red: 199/255.0, green: 146/255.0, blue: 224/255.0, alpha: 1)
        case "WooCommercePurple30":
            return UIColor(red: 175/255.0, green: 125/255.0, blue: 209/255.0, alpha: 1)
        case "WooCommercePurple40":
            return UIColor(red: 154/255.0, green: 105/255.0, blue: 199/255.0, alpha: 1)
        case "WooCommercePurple50":
            return UIColor(red: 127/255.0, green: 84/255.0, blue: 179/255.0, alpha: 1)
        case "WooCommercePurple60":
            return UIColor(red: 103/255.0, green: 67/255.0, blue: 153/255.0, alpha: 1)
        case "WooCommercePurple70":
            return UIColor(red: 83/255.0, green: 53/255.0, blue: 130/255.0, alpha: 1)
        case "WooCommercePurple80":
            return UIColor(red: 60/255.0, green: 40/255.0, blue: 97/255.0, alpha: 1)
        case "WooCommercePurple90":
            return UIColor(red: 39/255.0, green: 27/255.0, blue: 61/255.0, alpha: 1)
        case "WooCommercePurple100":
            return UIColor(red: 20/255.0, green: 14/255.0, blue: 31/255.0, alpha: 1)
        case "WooCommercePurple":
            return UIColor(red: 127/255.0, green: 84/255.0, blue: 179/255.0, alpha: 1)

        case "JetpackGreen0":
            return UIColor(red: 242/255.0, green: 247/255.0, blue: 231/255.0, alpha: 1)
        case "JetpackGreen5":
            return UIColor(red: 208/255.0, green: 239/255.0, blue: 173/255.0, alpha: 1)
        case "JetpackGreen10":
            return UIColor(red: 157/255.0, green: 222/255.0, blue: 115/255.0, alpha: 1)
        case "JetpackGreen20":
            return UIColor(red: 100/255.0, green: 202/255.0, blue: 67/255.0, alpha: 1)
        case "JetpackGreen30":
            return UIColor(red: 47/255.0, green: 180/255.0, blue: 31/255.0, alpha: 1)
        case "JetpackGreen40":
            return UIColor(red: 6/255.0, green: 158/255.0, blue: 8/255.0, alpha: 1)
        case "JetpackGreen50":
            return UIColor(red: 0/255.0, green: 135/255.0, blue: 16/255.0, alpha: 1)
        case "JetpackGreen60":
            return UIColor(red: 0/255.0, green: 113/255.0, blue: 23/255.0, alpha: 1)
        case "JetpackGreen70":
            return UIColor(red: 0/255.0, green: 91/255.0, blue: 24/255.0, alpha: 1)
        case "JetpackGreen80":
            return UIColor(red: 0/255.0, green: 69/255.0, blue: 21/255.0, alpha: 1)
        case "JetpackGreen90":
            return UIColor(red: 0/255.0, green: 48/255.0, blue: 16/255.0, alpha: 1)
        case "JetpackGreen100":
            return UIColor(red: 0/255.0, green: 28/255.0, blue: 9/255.0, alpha: 1)
        case "JetpackGreen":
            return UIColor(red: 47/255.0, green: 180/255.0, blue: 31/255.0, alpha: 1)
        default:
            return nil
        }
    }
}
