# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 365 # 1 year

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: false

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - "[Pri] High"
  - "[Pri] Blocking"
  - "good first issue"

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Label to use when marking as stale
staleLabel: "[Status] Stale"

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been marked as stale because:
  
   * It has been inactive for the past year.
   * It isn't in a project or a milestone.
   * It hasn’t been labeled `[Pri] Blocker`, `[Pri] High`, or `good first issue`.
  
  Please comment with an update if you believe this issue is still valid or if it can be closed.
  This issue will also be reviewed for validity and priority during regularly scheduled triage sessions.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 2

# Limit to only `issues` or `pulls`
only: issues
