public struct ZendeskSiteContainer: Decodable {
    public let sites: [ZendeskSite]
}

public struct ZendeskSite: Decodable {
    public let ID: Int
    public let zendeskMetadata: ZendeskMetadata

    private enum CodingKeys: String, CodingKey {
        case ID = "ID"
        case zendeskMetadata = "zendesk_site_meta"
    }
}

public struct ZendeskMetadata: Decodable {
    public let plan: String
    public let jetpackAddons: [String]

    private enum CodingKeys: String, CodingKey {
        case plan = "plan"
        case jetpackAddons = "addon"
    }
}

/// Errors generated by the metadata decoding process
public enum PlanServiceRemoteError: Error {
    // thrown when no metadata were found
    case noMetadata
}
