AllCops:
  Exclude:
    - DerivedData/**/*
    - Pods/**/*
    - vendor/**/*
    - WordPressAuthenticator/**/*
    - WordPressKit/**/*
  NewCops: enable

Metrics/BlockLength:
  # "xfiles" is a standin for `Fast-`, `Pod-`, and `Rake-file`
  Exclude: &xfiles
    - fastlane/Fastfile
    - fastlane/lanes/*.rb
    - Podfile
    - Rakefile

Metrics/MethodLength:
  Max: 30
  Exclude: *xfiles

Layout/LineLength:
  Max: 165
  Exclude: *xfiles

Layout/EmptyLines:
  Exclude: *xfiles

Style/MutableConstant:
  Exclude:
    # CocoaPods mutates some input values.
    # It's simpler to relax this rule than to address each individually by passing mutable copies.
    - Gutenberg/cocoapods_helpers.rb

Style/AsciiComments:
  Exclude: *xfiles

Naming/FileName:
  Exclude:
    - fastlane/Matchfile

Style/HashSyntax:
  EnforcedShorthandSyntax: never
