parent_config: https://raw.githubusercontent.com/Automattic/swiftlint-config/0f8ab6388bd8d15a04391825ab125f80cfb90704/.swiftlint.yml
remote_timeout: 10.0

opt_in_rules:
  - overridden_super_call
  - weak_delegate

overridden_super_call:
  severity: error

weak_delegate:
  severity: error
