# frozen_string_literal: true

install! 'cocoapods', warn_for_multiple_pod_sources: false
source 'https://cdn.cocoapods.org/'

platform :macos, '14.7'

workspace 'BuildTools.xcworkspace'

raise 'Please run CocoaPods via `bundle exec`' unless %w[BUNDLE_BIN_PATH BUNDLE_GEMFILE].any? { |k| ENV.key?(k) }

def swiftlint_version
  require 'yaml'

  YAML.load_file(File.join(__dir__, '..', '.swiftlint.yml'))['swiftlint_version']
end

abstract_target 'Tools' do
  pod 'SwiftLint', swiftlint_version
end
