# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.18.1
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-15.1

# This is the default pipeline – it will build and test the app
steps:
  - label: Log Outdated Pods
    plugins: *common_plugins
    agents:
        queue: mac
    env:
      IMAGE_ID: xcode-15.1
    command: ".buildkite/commands/log-outdated-pods.sh 24.3"
