# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.2.0
    - automattic/git-s3-cache#v1.1.0:
        bucket: "a8c-repo-mirrors"
        repo: "wordpress-mobile/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Remember to address all "FIXIT-13.1" comments when we'll update to new image.
    #
    # `xcode-13.4.1` note: The issue "FIXIT-13.1" addresses is still there in this image.
    # See: https://buildkite.com/automattic/wordpress-ios/builds/8187#01813c28-1c1d-4a25-95c0-0fdd6f2af399
    IMAGE_ID: xcode-13.4.1

# This is the default pipeline – it will build and test the app
steps:

  #################
  # Create Installable Builds for WP and JP
  #################
  # - label: "🛠 WordPress Installable Build"
  #   command: ".buildkite/commands/installable-build-wordpress.sh"
  #   env: *common_env
  #   plugins: *common_plugins
  #   if: "build.pull_request.id != null || build.pull_request.draft"
  #   notify:
  #     - github_commit_status:
  #         context: "WordPress Installable Build"

  # - label: "🛠 Jetpack Installable Build"
  #   command: ".buildkite/commands/installable-build-jetpack.sh"
  #   env: *common_env
  #   plugins: *common_plugins
  #   if: "build.pull_request.id != null || build.pull_request.draft"
  #   notify:
  #     - github_commit_status:
  #         context: "Jetpack Installable Build"

  #################
  # Build the app
  #################
  # - label: "🛠 Build for Testing"
  #   key: "build"
  #   command: ".buildkite/commands/build-for-testing.sh"
  #   env: *common_env
  #   plugins: *common_plugins
  #   notify:
  #     - github_commit_status:
  #         context: "Build for Testing"

  #################
  # Run Unit Tests
  #################
  - label: "🔬 Unit Tests"
    command: ".buildkite/commands/run-unit-tests.sh"
    # depends_on: "build"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
    notify:
      - github_commit_status:
          context: "Unit Tests"

  # TODO: Move Lint Translations elsewhere (on very top or very bottom?) so that "Build for Testing" and all the corresponding "* Tests" steps
  #       are next to one another instead of being "interrupted" in the step list by that "Lint Translations"
  #
  # TODO: Create a `group:` step to group both UI Tests steps together for nicer presentation on the page.

  #################
  # Lint Translations
  #################
  # - label: "🧹 Lint Translations"
  #   command: "gplint /workdir/WordPress/Resources/AppStoreStrings.po"
  #   plugins:
  #     - docker#v3.8.0:
  #         image: "public.ecr.aws/automattic/glotpress-validator:1.0.0"
  #   agents:
  #     queue: "default"
  #   notify:
  #     - github_commit_status:
  #         context: "Lint Translations"

  #################
  # UI Tests
  #################
  - label: "🔬 UI Tests (iPhone)"
    command: .buildkite/commands/run-ui-tests.sh WordPressUITests 'iPhone 13' 15.0
    # depends_on: "build"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
    notify:
      - github_commit_status:
          context: "UI Tests (iPhone)"

  - label: "🔬 UI Tests (iPad)"
    command: .buildkite/commands/run-ui-tests.sh WordPressUITests "iPad Air (5th generation)" 15.0
    # depends_on: "build"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
    notify:
      - github_commit_status:
          context: "UI Tests (iPad)"
