
# This is the default pipeline – it will build and test the app
steps:

  #################
  # Build the app
  #################
  - label: ":pipeline: Build"
    key: "build"
    command: |
      echo "--- 🔧 Setting up Gems"
      gem install bundler
      bundle install
      echo "--- 🔨 Setting up Pods"
      bundle exec pod install --repo-update
      echo "--- ✍️ Copy Files"
      cp fastlane/env/project.env-example .configure-files/project.env
      echo "--- 🛠 Building"
      bundle exec fastlane build_for_testing
      echo "--- 🗜 Zip Build Products"
      tar -cf build-products.tar DerivedData/Build/Products/
    artifact_paths:
      - build-products.tar

  #################
  # Run Unit Tests
  #################
  - label: "🧪 Unit Tests"
    command: |
      buildkite-agent artifact download build-products.tar .
      tar -xf build-products.tar
      bundle install
      bundle exec fastlane test_without_building name:WordPressUnitTests try_count:3
    depends_on: "build"

  #################
  # Lint Translations
  #################
  - label: "🧹 Lint Translations"
    command: "gplint /workdir/WordPress/Resources/AppStoreStrings.po"
    plugins:
      - docker#v3.8.0:
          image: "public.ecr.aws/automattic/glotpress-validator:1.0.0"
    agents:
      queue: "default"

  #################
  # UI Tests
  #################
  - label: "🧪 UI Tests (iPhone)"
    command: |
      buildkite-agent artifact download build-products.tar .
      tar -xf build-products.tar
      bundle install
      bundle exec pod install
      rake mocks &
      bundle exec fastlane test_without_building name:WordPressUITests try_count:3 device:"iPhone 11" ios-version:"14.1"
    depends_on: "build"
    agents:
      os: "macOS"

  - label: "🧪 UI Tests (iPad)"
    command: |
      buildkite-agent artifact download build-products.tar .
      tar -xf build-products.tar
      bundle install
      bundle exec pod install
      rake mocks &
      bundle exec fastlane test_without_building name:WordPressUITests try_count:3 device:"iPad Air (4th generation)" ios-version:"14.1"
    depends_on: "build"
    agents:
      os: "macOS"
