# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.2.0
    - automattic/git-s3-cache#v1.1.0:
        bucket: "a8c-repo-mirrors"
        repo: "wordpress-mobile/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-13 # Remember to address all 'FIXIT-13.1' comments when we'll update to new image
    FASTLANE_HIDE_PLUGINS_TABLE: 1 # Don't print noisy plugins table and save logs lines

# This is the default pipeline – it will build and test the app
steps:

  - label: "Test"
    command: echo $FASTLANE_HIDE_PLUGINS_TABLE
    env: *common_env
    plugins: *common_plugins

  - label: "Test some more"
    command: bundle exec fastlane cowabunga
    env: *common_env
    plugins: *common_plugins
