# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.6.0
    - automattic/git-s3-cache#v1.1.0:
        bucket: "a8c-repo-mirrors"
        repo: "wordpress-mobile/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Remember to address all "FIXIT-13.1" comments when we'll update to new image.
    #
    # `xcode-13.4.1` note: The issue "FIXIT-13.1" addresses is still there in this image.
    # See: https://buildkite.com/automattic/wordpress-ios/builds/8187#01813c28-1c1d-4a25-95c0-0fdd6f2af399
    IMAGE_ID: xcode-13.4.1

# This is the default pipeline – it will build and test the app
steps:
  - label: ":wordpress::testflight: WordPress Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build-wordpress.sh $BETA_RELEASE"
    env: *common_env
    plugins: *common_plugins

  # There is no App Center emojiy
  - label: ":wordpress::hockeyapp: WordPress Release Build (App Center)"
    command: ".buildkite/commands/release-build-wordpress-internal.sh"
    env: *common_env
    plugins: *common_plugins

  - label: ":jetpack::testflight: Jetpack Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build-jetpack.sh"
    env: *common_env
    plugins: *common_plugins
