# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#v1.6.0
    - automattic/git-s3-cache#v1.1.0:
        bucket: "a8c-repo-mirrors"
        repo: "wordpress-mobile/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-13 # Remember to address all 'FIXIT-13.1' comments when we'll update to new image

# This is the default pipeline – it will build and test the app
steps:

  #################
  # Create Installable Builds for WP and JP
  #################
  - label: "🛠 WordPress Installable Build"
    command: ".buildkite/commands/installable-build-wordpress.sh"
    env: *common_env
    plugins: *common_plugins
    if: "build.pull_request.id != null || build.pull_request.draft"
    notify:
      - github_commit_status:
          context: "WordPress Installable Build"

  - label: "🛠 Jetpack Installable Build"
    command: ".buildkite/commands/installable-build-jetpack.sh"
    env: *common_env
    plugins: *common_plugins
    if: "build.pull_request.id != null || build.pull_request.draft"
    notify:
      - github_commit_status:
          context: "Jetpack Installable Build"

  #################
  # Build the app
  #################
  - label: "🛠 Build for Testing"
    key: "build"
    command: ".buildkite/commands/build-for-testing.sh"
    env: *common_env
    plugins: *common_plugins
    notify:
      - github_commit_status:
          context: "Build for Testing"

  #################
  # Run Unit Tests
  #################
  - label: "🔬 Unit Tests"
    command: ".buildkite/commands/run-unit-tests.sh"
    depends_on: "build"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
    notify:
      - github_commit_status:
          context: "Unit Tests"

  #################
  # Lint Translations
  #################
  - label: "🧹 Lint Translations"
    command: "gplint /workdir/WordPress/Resources/AppStoreStrings.po"
    plugins:
      - docker#v3.8.0:
          image: "public.ecr.aws/automattic/glotpress-validator:1.0.0"
    agents:
      queue: "default"
    notify:
      - github_commit_status:
          context: "Lint Translations"

  #################
  # UI Tests
  #################
  - label: "🔬 UI Tests (iPhone)"
    command: .buildkite/commands/run-ui-tests.sh WordPressUITests 'iPhone 13' 15.0
    depends_on: "build"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
    notify:
      - github_commit_status:
          context: "UI Tests (iPhone)"

  - label: "🔬 UI Tests (iPad)"
    command: .buildkite/commands/run-ui-tests.sh WordPressUITests "iPad Air (4th generation)" 15.0
    depends_on: "build"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
    notify:
      - github_commit_status:
          context: "UI Tests (iPad)"
