# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.2.0
    - automattic/git-s3-cache#v1.1.0:
        bucket: "a8c-repo-mirrors"
        repo: "wordpress-mobile/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Remember to address all "FIXIT-13.1" comments when we'll update to new image.
    #
    # `xcode-13.4.1` note: The issue "FIXIT-13.1" addresses is still there in this image.
    # See: https://buildkite.com/automattic/wordpress-ios/builds/8187#01813c28-1c1d-4a25-95c0-0fdd6f2af399
    IMAGE_ID: xcode-13.4.1

# This is the default pipeline – it will build and test the app
steps:

  - label: "🔬 Screenshot Tests"
    command: ".buildkite/commands/run-unit-tests.sh"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
