agents:
  queue: mac
env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: Dummy
    command: echo "Hello, {{matrix}}!"
    matrix:
      - matrix value 1
      - matrix value 2
    env:
      # Note: When used standalone, {{matrix}} needs to be quoted or the parsing will fail.
      MATRIX_NAME_FOR_COMMIT_STATUS: "{{matrix}}"
    notify:
      - github_commit_status:
          context: "Dummy step with $${MATRIX_NAME_FOR_COMMIT_STATUS}"

  - label: Dummy step for commit status interpolation check
    command: echo "Hello, world!"
    env:
      VALUE_FOR_COMMIT_STATUS: test value from env
    notify:
      - github_commit_status:
          context: "Dummy step with $${VALUE_FOR_COMMIT_STATUS}"
