# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.6.0
    - automattic/git-s3-cache#v1.1.0:
        bucket: "a8c-repo-mirrors"
        repo: "wordpress-mobile/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Remember to address all "FIXIT-13.1" comments when we'll update to new image.
    #
    # `xcode-13.4.1` note: The issue "FIXIT-13.1" addresses is still there in this image.
    # See: https://buildkite.com/automattic/wordpress-ios/builds/8187#01813c28-1c1d-4a25-95c0-0fdd6f2af399
    IMAGE_ID: xcode-13.4.1

# Test to see how many of our agents fail to load the VMs as well as how
# many can get jobs at the same time
steps:
  - label: "1 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "2 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "3 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "4 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "5 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "6 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "7 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "8 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "9 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "10 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "11 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "12 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "13 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "14 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "15 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "16 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "17 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "18 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "19 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "20 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "21 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "22 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "23 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins

  - label: "24 / 24"
    command: |
      echo 'hello world'
    env: *common_env
    plugins: *common_plugins
