# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.13.0
    - automattic/git-s3-cache#v1.1.3:
        bucket: "a8c-repo-mirrors"
        repo: "wordpress-mobile/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-14.2

# This is the default pipeline – it will build and test the app
steps:

  #################
  # Create Prototype Builds for WP and JP
  #################
  - group: "🛠 Prototype Builds"
    steps:
      - label: "🛠 WordPress Prototype Build"
        command: ".buildkite/commands/prototype-build-wordpress.sh"
        env: *common_env
        plugins: *common_plugins
        if: "build.pull_request.id != null || build.pull_request.draft"
        notify:
          - github_commit_status:
              context: "WordPress Prototype Build"

      - label: "🛠 Jetpack Prototype Build"
        command: ".buildkite/commands/prototype-build-jetpack.sh"
        env: *common_env
        plugins: *common_plugins
        if: "build.pull_request.id != null || build.pull_request.draft"
        notify:
          - github_commit_status:
              context: "Jetpack Prototype Build"

  #################
  # Create Builds for Testing
  #################
  - group: "🛠 Builds for Testing"
    steps:
      - label: "🛠 :wordpress: Build for Testing"
        key: "build_wordpress"
        command: ".buildkite/commands/build-for-testing.sh wordpress"
        env: *common_env
        plugins: *common_plugins
        notify:
          - github_commit_status:
              context: "WordPress Build for Testing"

      - label: "🛠 :jetpack: Build for Testing"
        key: "build_jetpack"
        command: ".buildkite/commands/build-for-testing.sh jetpack"
        env: *common_env
        plugins: *common_plugins
        notify:
          - github_commit_status:
              context: "Jetpack Build for Testing"

  #################
  # Run Unit Tests
  #################
  - label: "🔬 :wordpress: Unit Tests"
    command: ".buildkite/commands/run-unit-tests.sh"
    depends_on: "build_wordpress"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
    notify:
      - github_commit_status:
          context: "Unit Tests"
      - slack:
          channels:
            - "#mobile-apps-tests-notif"
        if: build.state == "failed" && build.branch == "trunk"

  #################
  # UI Tests
  #################
  - group: "🔬 UI Tests"
    steps:
      - label: "🔬 :jetpack: UI Tests (iPhone)"
        command: .buildkite/commands/run-ui-tests.sh 'iPhone SE (3rd generation)'
        depends_on: "build_jetpack"
        env: *common_env
        plugins: *common_plugins
        artifact_paths:
          - "build/results/*"
        notify:
          - github_commit_status:
              context: "UI Tests (iPhone)"
          - slack:
              channels:
                - "#mobile-apps-tests-notif"
            if: build.state == "failed" && build.branch == "trunk"

      - label: "🔬 :jetpack: UI Tests (iPad)"
        command: .buildkite/commands/run-ui-tests.sh 'iPad Air (5th generation)'
        depends_on: "build_jetpack"
        env: *common_env
        plugins: *common_plugins
        artifact_paths:
          - "build/results/*"
        notify:
          - github_commit_status:
              context: "UI Tests (iPad)"
          - slack:
              channels:
                - "#mobile-apps-tests-notif"
            if: build.state == "failed" && build.branch == "trunk"

  #################
  # Linters
  #################
  - group: "Linters"
    steps:
      - label: "🧹 Lint Translations"
        command: "gplint /workdir/WordPress/Resources/AppStoreStrings.po"
        plugins:
          - docker#v3.8.0:
              image: "public.ecr.aws/automattic/glotpress-validator:1.0.0"
        agents:
          queue: "default"
        notify:
          - github_commit_status:
              context: "Lint Translations"
      # This step uses Danger to run RuboCop, but it's "agnostic" about it.
      # That is, it outwardly only mentions RuboCop, not Danger
      - label: ":rubocop: Lint Ruby Tooling"
        command: .buildkite/commands/rubocop-via-danger.sh
        plugins: *common_plugins
        agents:
          queue: "android"
      - label: ":sleuth_or_spy: Lint Localized Strings Format"
        command: .buildkite/commands/lint-localized-strings-format.sh
        plugins: *common_plugins
        env: *common_env
