# This pipeline is meant to be run via the Buildkite API, and is only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.2.0
    - automattic/git-s3-cache#v1.1.0:
        bucket: "a8c-repo-mirrors"
        repo: "wordpress-mobile/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-13.4.1

steps:

  - label: ":wordpress::testflight: WordPress Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build-wordpress.sh $BETA_RELEASE"
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"

  # There is no App Center emojiy
  - label: ":wordpress::hockeyapp: WordPress Release Build (App Center)"
    command: ".buildkite/commands/release-build-wordpress-internal.sh"
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"

  - label: ":jetpack::testflight: Jetpack Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build-jetpack.sh"
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"
