# This pipeline is meant to be run via the Buildkite API, and is only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.18.1
    - automattic/git-s3-cache#1.1.4:
        bucket: "a8c-repo-mirrors"
        repo: "automattic/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-14.3.1

steps:

  - label: ":wordpress: :testflight: WordPress Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build-wordpress.sh $BETA_RELEASE"
    # The TestFlight build has a priority of 2 so that it is higher than the AppCenter build
    priority: 2
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"

  - label: ":wordpress: :appcenter: WordPress Release Build (App Center)"
    command: ".buildkite/commands/release-build-wordpress-internal.sh"
    priority: 1
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"

  - label: ":jetpack: :testflight: Jetpack Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build-jetpack.sh"
    # The TestFlight build has a priority of 2 so that it is higher than the AppCenter build
    priority: 2
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"
