# This pipeline is meant to be run via the Buildkite API, and is only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.18.1
    - automattic/git-s3-cache#1.1.4:
        bucket: "a8c-repo-mirrors"
        repo: "automattic/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-15.1

steps:

  - label: "Test release build for hotfix "
    command: |
      echo "beta release parameter: $BETA_RELEASE"
      echo "beta release parameter: $BETA_RELEASE"
    env: *common_env
    plugins: *common_plugins
