# This pipeline is meant to be run via the Buildkite API, and is only used for release builds

env:
  IMAGE_ID: $IMAGE_ID

steps:

  - label: ":wordpress: :testflight: WordPress Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build-wordpress.sh $BETA_RELEASE"
    plugins: [$CI_TOOLKIT_PLUGIN]
    notify:
    - slack: "#build-and-ship"

  - label: ":jetpack: :testflight: Jetpack Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build-jetpack.sh"
    plugins: [$CI_TOOLKIT_PLUGIN]
    notify:
    - slack: "#build-and-ship"
