#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

# The ~> modifier is not currently used, but we check for it just in case
XCODE_VERSION=$(sed -E -n 's/^(~> )?(.*)/xcode-\2/p' .xcode-version)
export IMAGE_ID="$XCODE_VERSION"

export CI_TOOLKIT_PLUGIN="automattic/a8c-ci-toolkit#3.3.0"
