import Foundation
import WordPressData
import WordPressReader
import WordPressUI
import SwiftSoup

extension ReaderPost {

    /// - note: this is a workaround for https://github.com/wordpress-mobile/WordPress-iOS/issues/18975 and
    /// https://github.com/wordpress-mobile/WordPress-iOS/issues/20953. This code
    /// makes sure that you see the "Follow Conversation" button on P2s
    /// but not if you have "Emails me all comments" option enabled, which
    /// matches the behavior on the web.
    var canActuallySubscribeToComments: Bool {
        if canSubscribeComments {
            return true
        }
        if isP2Type {
            return !((topic as? ReaderSiteTopic)?.emailSubscription?.sendComments ?? false)
        }
        return false
    }

    func getSiteIconURL(size: Int) -> URL? {
        SiteIconViewModel.makeReaderSiteIconURL(iconURL: siteIconURL, siteID: siteID?.intValue, size: CGSize(width: size, height: size))
    }

    /// Find cached comment with given ID.
    ///
    /// - Parameter id: The comment id
    /// - Returns: The `Comment` object associated with the given id, or `nil` if none is found.
    @objc
    public func comment(withID id: NSNumber) -> WordPressData.Comment? {
        comment(withID: id.int32Value)
    }

    /// Find cached comment with given ID.
    ///
    /// - Parameter id: The comment id
    /// - Returns: The `Comment` object associated with the given id, or `nil` if none is found.
    func comment(withID id: Int32) -> WordPressData.Comment? {
        comments?.first { $0.commentID == id }
    }

    /// Get a cached site's ReaderPost with the specified ID.
    ///
    /// - Parameter postID: ID of the post.
    /// - Parameter siteID: ID of the site the post belongs to.
    /// - Returns: the matching `ReaderPost`, or `nil` if none is found.
    static func lookup(withID postID: NSNumber, forSiteWithID siteID: NSNumber, in context: NSManagedObjectContext) throws -> ReaderPost? {
        let request = NSFetchRequest<ReaderPost>(entityName: ReaderPost.classNameWithoutNamespaces())
        request.predicate = NSPredicate(format: "postID = %@ AND siteID = %@", postID, siteID)
        request.fetchLimit = 1
        return try context.fetch(request).first
    }

    /// Get a cached site's ReaderPost with the specified ID.
    ///
    /// - Parameter postID: ID of the post.
    /// - Parameter siteID: ID of the site the post belongs to.
    /// - Returns: the matching `ReaderPost`, or `nil` if none is found.
    @objc(lookupWithID:forSiteWithID:inContext:)
    public static func objc_lookup(withID postID: NSNumber, forSiteWithID siteID: NSNumber, in context: NSManagedObjectContext) -> ReaderPost? {
        try? lookup(withID: postID, forSiteWithID: siteID, in: context)
    }

    /// Returns the excerpt only if it was explicitly provided by the post author.
    ///
    /// The API always returns a `excerpt`, but it's usually auto-generated by
    /// truncating the post content. This method compares the summary against the
    /// beginning of the content — if the summary is just a prefix of the content
    /// (optionally ending with `[…]` or `…`), it's considered auto-generated
    /// and `nil` is returned.
    func getUserProvidedExcerpt() -> String? {
        guard let excerpt = mt_excerpt?.makePlainText(), !excerpt.isEmpty else {
            return nil
        }
        guard let content = contentForDisplay(), !content.isEmpty else {
            return excerpt
        }

        // Auto-generated excerpts end with a truncation marker
        if excerpt.hasSuffix("[…]") || excerpt.hasSuffix("…") {
            return nil
        }

        // If the content starts with the excerpt, it's auto-generated
        let plainContent = content.makePlainText()
        if plainContent.hasPrefix(excerpt.prefix(50)) {
            return nil
        }

        return excerpt
    }

    func makeExceptHTML() -> String {
        """
        <html>
        <body>
        <p>\(SwiftSoup.Entities.escape(summary ?? ""))</p>
        </body>
        </html>
        """
    }
}
