require 'dotenv'
Dotenv.load('~/.wpios-env.default')

screenshots_path "./screenshots/"
app_identifier "org.wordpress"

# Make sure to update these keys for a new version
app_version "16.6"

skip_binary_upload true
overwrite_screenshots true
phased_release true
