require 'dotenv'
Dotenv.load('~/.wpios-env.default')

screenshots_path "./screenshots/"
app_identifier "org.wordpress"

# Make sure to update these keys for a new version
app_version "16.2"

privacy_url({
  'default' => 'https://automattic.com/privacy/',
})

copyright('2020 Automattic Inc.')

skip_binary_upload true
overwrite_screenshots true
phased_release true
