# Uncomment the lines below you want to change by removing the # in the beginning
# Verify script has credentials

# A list of devices you want to take the screenshots from
devices([
 # "iPhone 7",
  # "iPhone 7 Plus",
#  "iPhone 5",
  "iPad Pro (12.9-inch)"
])

languages("fr-FR es-ES en-US en-CA en-AU it-IT ja-JP sv-SE pt-BR nl-NL de-DE id-ID ko-KR ru-RU cmn-Hans th-TH cmn-Hant tr-TR en-GB".split(" "))

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

scheme "WordPressScreenshotGeneration"

# clear_previous_screenshots true # remove the '#'' to clear all previously generated screenshots before creating new ones

# Where is your project (or workspace)? Provide the full path here
workspace "../../WordPress.xcworkspace"

localize_simulator true

# By default, the latest version should be used automatically. If you want to change it, do it here
# ios_version '8.1'

# Custom Callbacks

# setup_for_device_change do |device| 
#   puts "Preparing device: #{device}"
# end

# setup_for_language_change do |lang, device|
#   puts "Running #{lang} on #{device}"
#   system("./popuplateDatabase.sh")
# end

# teardown_language do |lang, device|
#   puts "Finished with #{lang} on #{device}"
# end

# teardown_device do |device|
#   puts "Cleaning device #{device}"
#   system("./cleanup.sh")
# end
