#!/bin/bash -eu

# Use this to run a Ruby script from a "Script Build Phase" from Xcode.
#
# Since shell scripts ran by Xcode  do not source the user shell profile, typical user setups like the configurations of `rbenv` or `rvm` would not be set up properly.
# This script check if either rbenv or rvm is installed on the Mac and runs the setup steps as appririate, before running the ruby script via `bundle exec`
#
# Usage:
#   `runRubyScript <script_name.rb> <optional_args>`
#
# Where <script_name.rb` can be either an absolute path, or a path relative to this runRubyScript wrapper script.
#
# Inspiration: https://mgrebenets.github.io/xcode/2019/04/04/xcode-build-phases-and-environment
#

# Add `rbenv` and `rvm` binaries to PATH, so that we support both
export PATH="$HOME/.rbenv/shims:$HOME/.rvm/bin:$PATH"
RUBY_VERSION="$(cat "${PROJECT_DIR}/../.ruby-version")"
if command -v rvm; then
  source "$(rvm "${RUBY_VERSION}" do rvm env --path | tail -n1)"
fi

# Run the script with bundle exec
echo "Running the script using 'bundle exec' ..."
cd "$(dirname "${BASH_SOURCE[0]}")"
bundle exec ruby "$@"
cd -
