#!/bin/sh

cd `dirname $0`

for lang in *.lproj; do
  lang=`basename $lang .lproj`
  if [ "$lang" == "en" ]; then
    continue
  fi
  code=$lang
  if [ "$lang" == "zh-Hans" ]; then
    code="zh-cn"
  fi
  echo "Downloading $code -> $lang..."
  curl -so $lang.lproj/Localizable.strings http://translate.wordpress.org/projects/ios/dev/$code/default/export-translations?format=strings
done

cd - > /dev/null