# frozen_string_literal: true

fastlane_require 'xcodeproj'
fastlane_require 'dotenv'
fastlane_require 'open-uri'
fastlane_require 'git'

UI.user_error!('Please run fastlane via `bundle exec`') unless FastlaneCore::Helper.bundler?

########################################################################
# Constants and Environment Variables
########################################################################

# Paths that are re-used across multiple lanes
PROJECT_ROOT_FOLDER = File.dirname(File.expand_path(__dir__))
WORKSPACE_PATH = File.join(PROJECT_ROOT_FOLDER, 'WordPress.xcworkspace')
DERIVED_DATA_PATH = File.join(PROJECT_ROOT_FOLDER, 'DerivedData')
BUILD_PRODUCTS_PATH = File.join(PROJECT_ROOT_FOLDER, 'Artifacts')
WORDPRESS_RELEASE_NOTES_PATH = File.join(PROJECT_ROOT_FOLDER, 'WordPress', 'Resources', 'release_notes.txt')
JETPACK_RELEASE_NOTES_PATH = File.join(PROJECT_ROOT_FOLDER, 'WordPress', 'Jetpack', 'Resources', 'release_notes.txt')

# Env file paths to load
ENV_FILE_NAME = '.wpios-env.default'
USER_ENV_FILE_PATH = File.join(Dir.home, ENV_FILE_NAME)
SECRETS_DIR = File.join(Dir.home, '.configure', 'wordpress-ios', 'secrets')
PROJECT_ENV_FILE_PATH = File.join(SECRETS_DIR, 'project.env')
APP_STORE_CONNECT_KEY_PATH = File.join(SECRETS_DIR, 'app_store_connect_fastlane_api_key.json')

# Other defines used across multiple lanes
REPOSITORY_NAME = 'WordPress-iOS'

WORDPRESS_BUNDLE_IDENTIFIER = 'org.wordpress'
WORDPRESS_EXTENSIONS_BUNDLE_IDENTIFIERS = %w[
  WordPressShare
  WordPressDraftAction
  WordPressNotificationServiceExtension
  WordPressNotificationContentExtension
].map { |suffix| "#{WORDPRESS_BUNDLE_IDENTIFIER}.#{suffix}" }
ALL_WORDPRESS_BUNDLE_IDENTIFIERS = [WORDPRESS_BUNDLE_IDENTIFIER, *WORDPRESS_EXTENSIONS_BUNDLE_IDENTIFIERS].freeze

JETPACK_BUNDLE_IDENTIFIER = 'com.automattic.jetpack'
JETPACK_EXTENSIONS_BUNDLE_IDENTIFIERS = %w[
  JetpackShare
  JetpackDraftAction
  JetpackStatsWidgets
  JetpackNotificationServiceExtension
  JetpackIntents
].map { |suffix| "#{JETPACK_BUNDLE_IDENTIFIER}.#{suffix}" }
ALL_JETPACK_BUNDLE_IDENTIFIERS = [JETPACK_BUNDLE_IDENTIFIER, *JETPACK_EXTENSIONS_BUNDLE_IDENTIFIERS].freeze

# Environment Variables — used by lanes but also potentially actions
Dotenv.load(USER_ENV_FILE_PATH)
Dotenv.load(PROJECT_ENV_FILE_PATH)
GITHUB_REPO = 'wordpress-mobile/wordpress-iOS'
DEFAULT_BRANCH = 'trunk'
ENV['PROJECT_NAME'] = 'WordPress'
PUBLIC_CONFIG_FILE = File.join(PROJECT_ROOT_FOLDER, 'config', 'Version.Public.xcconfig')
ENV['PUBLIC_CONFIG_FILE'] = PUBLIC_CONFIG_FILE
INTERNAL_CONFIG_FILE = File.join(PROJECT_ROOT_FOLDER, 'config', 'Version.internal.xcconfig')
ENV['INTERNAL_CONFIG_FILE'] = INTERNAL_CONFIG_FILE
ENV['PROJECT_ROOT_FOLDER'] = "#{PROJECT_ROOT_FOLDER}/"
ENV['APP_STORE_STRINGS_FILE_NAME'] = 'AppStoreStrings.po'
ENV['FASTLANE_WWDR_USE_HTTP1_AND_RETRIES'] = 'true'

# Instanstiate versioning classes
VERSION_CALCULATOR = Fastlane::Wpmreleasetoolkit::Versioning::MarketingVersionCalculator.new
VERSION_FORMATTER = Fastlane::Wpmreleasetoolkit::Versioning::FourPartVersionFormatter.new
BUILD_CODE_FORMATTER = Fastlane::Wpmreleasetoolkit::Versioning::FourPartBuildCodeFormatter.new
PUBLIC_VERSION_FILE = Fastlane::Wpmreleasetoolkit::Versioning::IOSVersionFile.new(xcconfig_path: PUBLIC_CONFIG_FILE)

# Instantiate internal versioning classes
INTERNAL_BUILD_CODE_CALCULATOR = Fastlane::Wpmreleasetoolkit::Versioning::DateBuildCodeCalculator.new
INTERNAL_VERSION_FILE = Fastlane::Wpmreleasetoolkit::Versioning::IOSVersionFile.new(xcconfig_path: INTERNAL_CONFIG_FILE)

# Use this instead of getting values from ENV directly. It will throw an error if the requested value is missing
def get_required_env(key)
  UI.user_error!("Environment variable '#{key}' is not set. Have you setup #{USER_ENV_FILE_PATH} correctly?") unless ENV.key?(key)
  ENV.fetch(key, nil)
end

def gutenberg_config!
  require 'yaml'

  gutenberg_config_path = File.join(PROJECT_ROOT_FOLDER, 'Gutenberg', 'config.yml')

  UI.user_error!("Could not find config YAML at path #{gutenberg_config_path}") unless File.exist?(gutenberg_config_path)

  begin
    YAML.safe_load(File.read(gutenberg_config_path), symbolize_names: true)
  rescue StandardError => e
    UI.user_error!("Could not parse config YAML. Failed with: #{e.message}")
  end
end

########################################################################
# Version Methods
########################################################################

# Returns the release version of the app in the format `1.2` or `1.2.3` if it is a hotfix
#
def current_release_version
  # Read the current release version from the .xcconfig file and parse it into an AppVersion object
  current_version = VERSION_FORMATTER.parse(PUBLIC_VERSION_FILE.read_release_version)
  # Return the formatted release version
  VERSION_FORMATTER.release_version(current_version)
end

# Returns the internal release version of the app in the format `1.2` or `1.2.3` if it is a hotfix
#
def current_internal_release_version
  # Read the current release version from the .xcconfig file and parse it into an AppVersion object
  current_version = VERSION_FORMATTER.parse(INTERNAL_VERSION_FILE.read_release_version)
  # Return the formatted release version
  VERSION_FORMATTER.release_version(current_version)
end

#  Returns the next release version of the app in the format `1.2` or `1.2.3` if it is a hotfix
#
def next_release_version
  # Read the current release version from the .xcconfig file and parse it into an AppVersion object
  current_version = VERSION_FORMATTER.parse(PUBLIC_VERSION_FILE.read_release_version)
  # Calculate the next release version
  next_calculated_release_version = VERSION_CALCULATOR.next_release_version(version: current_version)
  # Return the formatted release version
  VERSION_FORMATTER.release_version(next_calculated_release_version)
end

# Returns the current build code of the app
#
def current_build_code
  # Read the current build code from the .xcconfig file and parse it into an AppVersion object
  # The AppVersion is used because WP/JPiOS uses the four part (1.2.3.4) build code format, so the version
  # calculator can be used to calculate the next four-part version
  version = VERSION_FORMATTER.parse(PUBLIC_VERSION_FILE.read_build_code(attribute_name: 'VERSION_LONG'))
  # Return the formatted build code
  BUILD_CODE_FORMATTER.build_code(version:)
end

# Returns the current internal build code of the app
#
def current_internal_build_code
  # Read the current build code from the .xcconfig file and parse it into an AppVersion object
  # The AppVersion is used because WP/JPiOS uses the four part (1.2.3.4) build code format, so the version
  # calculator can be used to calculate the next four-part version
  version = VERSION_FORMATTER.parse(INTERNAL_VERSION_FILE.read_build_code(attribute_name: 'VERSION_LONG'))
  # Return the formatted build code
  BUILD_CODE_FORMATTER.build_code(version:)
end

# Returns the build code of the app for the code freeze. It is the release version name plus sets the build number to 0
#
def code_freeze_build_code
  # Read the current build code from the .xcconfig file and parse it into an AppVersion object
  # The AppVersion is used because WP/JPiOS uses the four part (1.2.3.4) build code format, so the version
  # calculator can be used to calculate the next four-part version
  current_release_version = VERSION_FORMATTER.parse(INTERNAL_VERSION_FILE.read_release_version)
  # Calculate the next release version, which will be used as the basis of the new build code
  code_freeze_build_code = VERSION_CALCULATOR.next_release_version(version: current_release_version)
  # Return the formatted build code
  BUILD_CODE_FORMATTER.build_code(version: code_freeze_build_code)
end

# Returns the internal build code of the app for the code freeze. It is the release version name plus sets the build
# number to 0
#
def code_freeze_internal_build_code
  # Read the current build code from the .xcconfig file and parse it into an AppVersion object
  # The AppVersion is used because WP/JPiOS uses the four part (1.2.3.4) build code format, so the version
  # calculator can be used to calculate the next four-part version
  current_release_version = VERSION_FORMATTER.parse(PUBLIC_VERSION_FILE.read_release_version)
  # Calculate the next release version, which will be used as the basis of the new build code
  code_freeze_build_code = VERSION_CALCULATOR.next_release_version(version: current_release_version)
  code_freeze_build_code = INTERNAL_BUILD_CODE_CALCULATOR.next_build_code(version: code_freeze_build_code)
  # Return the formatted build code
  BUILD_CODE_FORMATTER.build_code(version: code_freeze_build_code)
end

# Returns the build code of the app for the code freeze. It is the hotfix version name plus sets the build number to 0
#
def hotfix_build_code(release_version:)
  version = VERSION_FORMATTER.parse(release_version)
  # Return the formatted build code
  BUILD_CODE_FORMATTER.build_code(version:)
end

# Returns the next build code of the app
#
def next_build_code
  # Read the current build code from the .xcconfig file and parse it into an AppVersion object
  # The AppVersion is used because WP/JPiOS uses the four part (1.2.3.4) build code format, so the version
  # calculator can be used to calculate the next four-part version
  current_build_code = VERSION_FORMATTER.parse(PUBLIC_VERSION_FILE.read_build_code(attribute_name: 'VERSION_LONG'))
  # Calculate the next build code
  next_build_code = VERSION_CALCULATOR.next_build_number(version: current_build_code)
  # Return the formatted build code
  BUILD_CODE_FORMATTER.build_code(version: next_build_code)
end

# Returns the next internal build code of the app
#
def next_internal_build_code
  # Read the current build code from the .xcconfig file and parse it into an AppVersion object
  # The AppVersion is used because WP/JPiOS uses the four part (1.2.3.4) build code format, so the version
  # calculator can be used to calculate the next four-part version
  current_build_code = VERSION_FORMATTER.parse(PUBLIC_VERSION_FILE.read_build_code(attribute_name: 'VERSION_LONG'))
  # Calculate the next build code
  next_build_code = INTERNAL_BUILD_CODE_CALCULATOR.next_build_code(version: current_build_code)
  # Return the formatted build code
  BUILD_CODE_FORMATTER.build_code(version: next_build_code)
end

# Returns the next internal hotfix build code of the app
#
def internal_hotfix_build_code(release_version:)
  # Read the current build code from the .xcconfig file and parse it into an AppVersion object
  # The AppVersion is used because WP/JPiOS uses the four part (1.2.3.4) build code format, so the version
  # calculator can be used to calculate the next four-part version
  current_build_code = VERSION_FORMATTER.parse(release_version)
  # Calculate the next build code
  next_build_code = INTERNAL_BUILD_CODE_CALCULATOR.next_build_code(version: current_build_code)
  # Return the formatted build code
  BUILD_CODE_FORMATTER.build_code(version: next_build_code)
end

########################################################################
# Group buildkite logs by action
########################################################################

# A module that defines methods to be used as overrides to `Fastlane::Actions`
# module methods.
module FastlaneActionLogGroup
  def print_group(action_name)
    return if %w[is_ci].include?(action_name)

    puts "~~~ :fastlane: #{ENV.fetch('FASTLANE_LANE_NAME', '[root]')} >> #{action_name}"
  end

  def execute_action(action_name)
    print_group(action_name)
    super(action_name)
  end
end

if ENV.key?('BUILDKITE')
  Fastlane::Actions.singleton_class.class_eval do
    prepend FastlaneActionLogGroup
  end
end

########################################################################
# Imports domain-specific lanes
########################################################################

import 'lanes/build.rb'
import 'lanes/codesign.rb'
import 'lanes/localization.rb'
import 'lanes/release.rb'
import 'lanes/screenshots.rb'

########################################################################

default_platform(:ios)

before_all do |lane|
  # Skip these checks/steps for test lane (not needed for testing)
  next if lane == :test_without_building

  # Fixes weird Keychain bugs
  setup_ci

  # Check that the env files exist
  # rubocop:disable Style/IfUnlessModifier
  unless is_ci || File.file?(USER_ENV_FILE_PATH)
    example_path = 'fastlane/env/user.env-example '
    UI.user_error! "#{ENV_FILE_NAME} not found: Please copy #{example_path} to #{USER_ENV_FILE_PATH} and fill in the values."
  end

  unless File.file?(PROJECT_ENV_FILE_PATH)
    UI.user_error!("project.env not found at #{PROJECT_ENV_FILE_PATH}: Make sure your configuration is up to date with `rake dependencies`")
  end
  # rubocop:enable Style/IfUnlessModifier
end
