#!/bin/sh

if [ $# != 1 ]; then
  echo "Usage: $0 path/to/images.xcassets"
  exit 1
fi

self=`basename $0`

cat <<-EOF
import UIKit

// Automatically generated by \`$self\`

extension UIImage {
    enum AppImage: String {
EOF

for path in `ls $1/*.imageset/Contents.json`; do
  # File name, without extension, to pass to UIImage
  imageName=`echo $path | sed -e "s/.imageset.*//;s/^.*\///"`
  # Enum value, camel cased, starting with a lowercase letter to match Swift
  # style
  enumValue=`echo $imageName | perl -pe "s/[-_](.)/\u\1/g;s/^(.)/\l\1/g"`
  echo "        case $enumValue = \"$imageName\""
done

cat <<-EOF
    }

    convenience init(appImage: AppImage) {
        self.init(named: appImage.rawValue)!
    }
}
EOF

