steps:
  - label: Complete Code Freeze
    plugins:
      - automattic/a8c-ci-toolkit#2.18.2
    # The code freeze completion needs to run on macOS because it uses genstrings under the hood
    agents:
        queue: mac
    env:
      IMAGE_ID: xcode-15.1
    command: ".buildkite/commands/complete-code-freeze.sh $RELEASE_VERSION"
