# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.17.0

steps:
  - label: "Finalize release"
    plugins: *common_plugins
    command: |
      .buildkite/commands/configure-git-for-release-management.sh
      .buildkite/commands/checkout-release-branch.sh

      install_gems

      cp gradle.properties-example gradle.properties

      bundle exec fastlane finalize_release skip_confirm:true
