steps:
  - label: Complete Code Freeze
    plugins:
      - automattic/a8c-ci-toolkit#2.18.2
    # The beta needs to run on macOS because it uses genstrings under the hood
    agents:
        queue: mac
    env:
      IMAGE_ID: xcode-14.3.1
    command: |
      echo '--- :git: Configure Git for release management'
      .buildkite/commands/configure-git-for-release-management.sh

      echo '--- :ruby: Setup Ruby tools'
      install_gems

      echo '--- :shipit: Deploy new beta'
      bundle exec fastlane new_beta_release skip_confirm:true
