steps:
  - label: New Beta Deployment
    plugins:
      - $CI_TOOLKIT_PLUGIN
    # The beta needs to run on macOS because it uses genstrings under the hood
    agents:
        queue: mac
    env:
      IMAGE_ID: $IMAGE_ID
    command: |
      echo '--- :git: Configure Git for release management'
      .buildkite/commands/configure-git-for-release-management.sh

      echo '--- :ruby: Setup Ruby tools'
      install_gems

      echo '--- :closed_lock_with_key: Access secrets'
      bundle exec fastlane run configure_apply

      echo '--- :shipit: Deploy new beta'
      bundle exec fastlane new_beta_release skip_confirm:true
    retry:
      manual:
        # If those jobs fail, one should always prefer re-triggering a new build from ReleaseV2 rather than retrying the individual job from Buildkite
        allowed: false
